### ISSUE TITLE
Pls add Oranges to the grocery list

### ISSUE THREAD

**Issue by KazimMalik** [KazimMalik/TESTING-KAZIM-DELETE#2]
_You can add Oranges to the Grocerylist.txt list now at 4_

![Oranges_-_whole-halved-segment](https://user-images.githubusercontent.com/79874638/114445017-c94e2300-9b8c-11eb-8cbd-6c1e47ad620b.gif)

@Lslemus

**Comment by Lslemus** [comment]
I have fixed this in 587698900078c6750b365e17b0b4c4b179321275
